name = "dilithiumcoin"
main = ".open-next/worker.js"
compatibility_date = "2025-03-25"
compatibility_flags = ["nodejs_compat"]

[[routes]]
pattern = "dilithiumcoin.com"
custom_domain = true

[[routes]]
pattern = "miner.dilithiumcoin.com"
custom_domain = true

[assets]
directory = ".open-next/assets"
binding = "ASSETS"
